export default {
  ra: {
    action: {
      add_filter: "הוסף סינון",
      add: "הוסף",
      back: "חזור",
      bulk_actions: "פריט אחד נבחר |||| %{smart_count} פריטים נבחרו",
      cancel: "ביטול",
      clear_array_input: "נקה את הרשימה",
      clear_input_value: "נקה ערך",
      clone: "שכפל",
      confirm: "אשר",
      create: "צור",
      create_item: "צור %{item}",
      delete: "מחק",
      edit: "ערוך",
      export: "יצא",
      list: "רשימה",
      refresh: "רענן",
      remove_filter: "הסר סינון",
      remove_all_filters: "הסר את כל המסננים",
      remove: "מחק",
      save: "שמור",
      search: "חפש",
      select_all: "בחר הכל",
      select_row: "בחר שורה זו",
      show: "הצג",
      sort: "מיין",
      undo: "בטל",
      unselect: "ביטול בחירה",
      expand: "הרחב",
      close: "סגירה",
      open_menu: "פתח תפריט",
      close_menu: "סגור תפריט",
      update: "עדכן",
      move_up: "הזז למעלה",
      move_down: "הזז למטה",
      open: "פתח",
      toggle_theme: "החלף מצב בהיר/כהה",
      select_columns: "עמודות",
      update_application: "טען מחדש את האפליקציה",
    },
    boolean: {
      true: "כן",
      false: "לא",
      null: " ",
    },
    configurable: {
      customize: "התאם אישית",
      configureMode: "התאם דף זה",
      inspector: {
        title: "מאפיינים",
        content: "עמוד עם העכבר על רכיבי הממשק כדי לשנות את מאפייניהם",
        reset: "אפס הגדרות",
        hideAll: "הסתר הכל",
        showAll: "הצג הכל",
      },
      Datagrid: {
        title: "טבלת נתונים",
        unlabeled: "ימודה ללא תווית #%{column}",
      },
      SimpleForm: {
        title: "טופס",
        unlabeled: "שדה ללא תווית #%{input}",
      },
      SimpleList: {
        title: "רשימה",
        primaryText: "טקסט ראשי",
        secondaryText: "טקסט משני",
        tertiaryText: "טקסט שלישוני",
      },
    },
    page: {
      create: "צור %{name}",
      dashboard: "לוח המחוונים",
      edit: "%{name} #%{id}",
      error: "שגיאה התרחשה",
      list: "רשימת %{name}",
      loading: "טוען",
      not_found: "לא קיים",
      show: "%{name} #%{id}",
      empty: "אין %{name} עדיין.",
      invite: "תרצה להוסיף אחד?",
    },
    input: {
      file: {
        upload_several: "גרור מספר קבצים להעלאה או לחץ לבחור אחד.",
        upload_single: "גרור קובץ להעלאה או לחץ לבחור אחד.",
      },
      image: {
        upload_several: "גרור מספר תמונות להעלאה או לחץ לבחור אחת.",
        upload_single: "גרור תמונה להעלאה או לחץ לבחור אחת.",
      },
      references: {
        all_missing: "ישויות הקשר לא נמצאו.",
        many_missing: "לפחות אחת מישויות הקשר אינה זמינה יותר.",
        single_missing: "ישות הקשר אינה זמינה יותר.",
      },
      password: {
        toggle_visible: "הסתר סיסמה",
        toggle_hidden: "הצג סיסמה",
      },
    },
    message: {
      about: "אודות",
      are_you_sure: "האם את/ה בטוח/ה ?",
      bulk_delete_content:
        "האם אתה בטוח שברצונך למחוק %{name}? |||| האם אתה בטוח שברצונך למחוק %{smart_count} פריטים?",
      bulk_delete_title: "מחק %{name} |||| מחק %{smart_count} %{name} פריטים",
      bulk_update_content:
        "האם בטוח לעדכן את  %{name}? |||| האם בטוח לעדכן את %{smart_count} הפריטים?",
      bulk_update_title: "עדכן את %{name} |||| עדכן את %{smart_count} %{name}",
      clear_array_input: "בטוח למחוק את כל הרשימה?",
      delete_content: "האם אתה בטוח שברצונך למחוק את הפריט הזה?",
      delete_title: "מחק %{name} #%{id}",
      details: "פרטים",
      error: "קרתה שגיאת תקשורת והבקשה שלך לא הסתיימה.",
      invalid_form: "הטופס אינו תקין. אנא תקן את שגיאותיך",
      loading: "העמוד טוען, אנא המתן",
      no: "לא",
      not_found: "הכנסת כתובת שגויה או לחצת על קישור לא תקין",
      yes: "כן",
      unsaved_changes: "חלק מהשינויים שלך לא נשמרו, האם להתעלם מהם?",
    },
    navigation: {
      no_results: "לא נמצאו תוצאות",
      no_more_results: "עמוד %{page} מחוץ לתחום. אנא נסה את העמוד הקודם.",
      page_out_of_boundaries: "עמוד %{page} מחוץ לתחום",
      page_out_from_end: "לא ניתן להמשיך מעבר לעמוד האחרון",
      page_out_from_begin: "לא ניתן לגשת לפני העמוד הראשון",
      page_range_info: "%{offsetBegin}-%{offsetEnd} מתוך %{total}",
      partial_page_range_info:
        "%{offsetBegin}-%{offsetEnd} מתוך מעל ל- %{offsetEnd}",
      current_page: "עמוד %{page}",
      page: "עבור לעמוד %{page}",
      first: "עבור לעמוד הראשון",
      last: "עבור לעמוד האחרון",
      next: "עבור לעמוד הבא",
      previous: "עבור לעמוד הקודם",
      page_rows_per_page: "מספר שורות לעמוד:",
      next: "הבא",
      prev: "הקודם",
      skip_nav: "דלג לתוכן",
    },
    sort: {
      sort_by: "מיין לפי %{field} %{order}",
      ASC: "עולה",
      DESC: "יורד",
    },
    auth: {
      auth_check_error: "התחבר לחשבון כדי להמשיך",
      user_menu: "פרופיל",
      username: "שם משתמש",
      password: "סיסמא",
      sign_in: "כניסה",
      sign_in_error: "הכניסה נכשלה, אנא נסו שנית",
      logout: "התנתקות",
    },
    notification: {
      updated: "פריט עודכן בהצלחה",
      created: "פריט נוצר בהצלחה",
      deleted: "פריט נמחק בהצלחה",
      bad_item: "פריט לא תקין",
      item_doesnt_exist: "פריט לא קיים",
      http_error: "שגיאה בהתקשרות מול השרת",
      data_provider_error: "שגיאת dataProvider. בדוק את הקונסול לפרטים נוספים.",
      i18n_error: "לא ניתן לטעון תרגום לשפה הנבחרת",
      canceled: "הפעולה בוטלה",
      logged_out: "הנך מנותק, אנא התחבר מחדש.",
      not_authorized: "אינך מורשה לגשת לנתון זה.",
      application_update_available: "גירסה חדשה זמינה.",
    },
    validation: {
      required: "חובה",
      minLength: "חייב להכיל לפחות %{min} תווים",
      maxLength: "יכול להכיל לכל היותר %{max} תווים",
      minValue: "חייב להיות לפחות %{min}",
      maxValue: "חייב להיות %{max} או פחות",
      number: "חייב להיות מספר",
      email: 'כתובת דוא"ל לא תקנית',
      oneOf: "חייב להיות מאחת האפשרויות הבאות: %{options}",
      regex: "חייב להתאים לתבנית ספציפית (ביטוי רגולרי): %{pattern}",
      unique: "חייב להיות ייחודי",
    },
    saved_queries: {
      label: "שאילתות שמורות",
      query_name: "שם שאילתא",
      new_label: "שמור שאילתא נוכחית...",
      new_dialog_title: "שמור שאילתא נוכחית בשם",
      remove_label: "הסר שאילתא שמורה",
      remove_label_with_name: 'הסר שאילתא "%{name}"',
      remove_dialog_title: "למחוק שאילתא שמורה?",
      remove_message:
        "האם אתה בטוח שאתה רוצה למחוק פריט זה מרשימת השאילתות השמורות?",
      help: "סנן את הרשימה ושמור את השאילתא להמשך",
    },
  },
};
